#include <bits/stdc++.h>

#define va 			and
#define tudong 		auto
#define phavo 		break
#define truonghop	case
#define bat			catch
#define chu			char
#define loai		class
#define hangso		const
#define	tieptuc		continue
#define lam			do
#define doi			double
#define macdinh		default
#define khac		else
#define sai			false
#define noi			float
#define cho			for
#define diden		goto
#define neu			if
#define nguyen		int		 
#define dai			long
#define chinh		main
#define khonggian	namespace
#define moi 		new
#define khong		not
#define phep		operator
#define hoac		or
#define riengtu		private		
#define congkhai	public
#define trave		return
#define ngan		short
#define codau		signed
#define	doloncua	sizeof
#define tinh		static
#define xau			string
#define cautruc		struct
#define chuyen		switch
#define mau			template
#define nay			this
#define nem			throw
#define dung		true
#define thu			try
#define dnkieu		typedef
#define khongdau	unsigned
#define sudung		using
#define trong		void
#define trongkhi	while
#define doc			cin
#define in			cout
#define sonhohon	min
#define solonhon	max
#define xa			endl
#define danhsach	list
#define nhet_sau	push_back
#define xoa			erase
#define tim			find
#define batdau		begin
#define ketthuc		endl
#define tieuchuan	std

sudung khonggian tieuchuan;